### ISSUE TITLE
Do we want Group.variables?

### ISSUE THREAD

**Issue by boite** [droid-php/droid-model#4]
HostGroup uses VariableTrait and YamlLoader populates HostGroup.variables, but they are never used (except in InventoryCommand which merely prints them).

We recently made Host.variables usable for overriding Target, Project and Module variables and perhaps we should do the same thing for groups.  It's not a straightforward task because of the structure of TaskRunner, but one thing we could do is to hijack HostGroup.addHost and do

```
$host->variables = array_replace_recursive($this->variables, $host->variables);
```

thus, hosts would take on their group variables during droid's start-up phase.

The only problem with Group.variables is the weirdness that would ensue if a host is in multiple groups: groups defined later would override the variables of groups defined earlier. Not a good situation.

**Comment by joostfaassen** [comment]
I can see some use-cases for group.variables.
As for implementation: I think it's most clean if we keep the variables attached to the group, and not merge them into the host variables on addHost. It allows us to show the actual configuration to the user, and he/she wouldn't have to wonder why a certain variable is set to it's current value.

Can't we merge the group variables right before merging the host variables in the TaskRunner?

The ordering and potential confusion arising from a host being a member will remain either way. In practice I don't think it'll be an issue. You'd use a group or host level variable only to override a default at the project level. If you'd really need switch toggles at project level and again at group and/or host level's, probably there's room for improvement in the design of your droid project :)

**Comment by boite** [comment]
> Can't we merge the group variables right before merging the host variables in the TaskRunner?

Yes, we can.

**Comment by boite** [comment]
Done in v1.20.0
